# [project]
# name = "multichat-ai"

[auth]
enabled = true

[api]
enabled = true
port = 54321
schemas = ["public", "auth"]
extra_search_path = ["public"]

[db]
port = 54322

[analytics]
enabled = true
